version: "3.8"
services:

  # holds dictionary objects and matches to users.
  db:
    image: mongo:4.0-xenial
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - styktin:/data/db
    restart: on-failure

  # crunches queries and between frontend and db.
  dic-fulfillment:
    build: ./dic-fulfillment
    container_name: dic-fulfillment
    environment:
      MONGO_URL: mongodb://db/
      FLASK_APP: main
      FLASK_DEBUG: 1
    ports:
      - 5000:5000
    env_file: .env
    volumes: ['./dic-fulfillment:/home/app']
    restart: on-failure

  # next.js app front-end.
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/frontend
      - /home/frontend/node_modules
      - /home/frontend/.next
      - /home/pages
    env_file: .env

    restart: always

  # routes queries to appropriate points.
  reverse-proxy:
    image: nginx:1.23.1
    container_name: nginx
    depends_on:
      - dic-fulfillment
      - frontend
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: on-failure
volumes:
  styktin:
